apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/metallb/metallb-operator.git/config/webhook-on-openshift?ref=v0.12.0
  - https://github.com/metallb/metallb-operator.git/config/metallb_rbac?ref=v0.12.0
patchesStrategicMerge:
  - bgptypefrr.yaml
namespace: metallb-system
